# Generated by Django 4.1.1 on 2023-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_snippet_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='privacy',
            field=models.BooleanField(choices=[('Публичный', 'Публичный'), ('Частный', 'Частный')]),
        ),
    ]
