# Generated by Django 4.1.1 on 2023-02-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_snippet_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='privacy',
            field=models.BooleanField(choices=[(False, 'Публичный'), (True, 'Частный')]),
        ),
    ]
