# Generated by Django 4.1.1 on 2023-02-16 17:16

import MainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_comment_image_alter_comment_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[MainApp.models.Comment.validate_image]),
        ),
    ]
