# Generated by Django 4.1.1 on 2023-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_snippet_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='voted',
            new_name='voted_up',
        ),
        migrations.AddField(
            model_name='snippet',
            name='voted_down',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
