# Generated by Django 4.1.1 on 2023-02-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_rename_voted_snippet_voted_up_snippet_voted_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='voted_down',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='voted_up',
        ),
    ]
